#!/bin/bash
set -euo pipefail

BK_ZIPSTASH_BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"
BK_ZIPSTASH_ID="${BUILDKITE_PLUGIN_ZIPSTASH_ID:-}"

source "${BK_ZIPSTASH_BASEDIR}/lib/shared.bash"

CACHE_KEY="$(expand_templates "$BUILDKITE_PLUGIN_ZIPSTASH_KEY")"

zipstash save \
  --token-source buildkite \
  --key "${CACHE_KEY}" \
  --local_branch="${BUILDKITE_BRANCH}" \
  --local_repository="${BUILDKITE_PLUGIN_ZIPSTASH_REPO}" \
  --endpoint "${BUILDKITE_PLUGIN_ZIPSTASH_ENDPOINT}" \
  --path "${BUILDKITE_PLUGIN_ZIPSTASH_PATHS}"
