#!/bin/bash
set -euo pipefail

BK_ZIPSTASH_BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"
BK_ZIPSTASH_ID="${BUILDKITE_PLUGIN_ZIPSTASH_ID:-}"
BK_ZIPSTASH_CLEAN=${BUILDKITE_PLUGIN_ZIPSTASH_CLEAN:-false}

source "${BK_ZIPSTASH_BASEDIR}/lib/shared.bash"

CACHE_KEY="$(expand_templates "$BUILDKITE_PLUGIN_ZIPSTASH_KEY")"

zipstash restore \
  --token-source buildkite \
  --key "${CACHE_KEY}" \
  --branch="${BUILDKITE_BRANCH}" \
  --name="${BUILDKITE_PLUGIN_ZIPSTASH_REPO}" \
  --owner="${BUILDKITE_ORGANIZATION_SLUG}" \
  --endpoint "${BUILDKITE_PLUGIN_ZIPSTASH_ENDPOINT}" \
  --clean="${BK_ZIPSTASH_CLEAN}" \
  --path "${BUILDKITE_PLUGIN_ZIPSTASH_PATHS}"
